<?php
/**
 * Laravel Deployer - Initial Deployment Bootstrap
 * 
 * This standalone file handles first-time deployment when Laravel isn't installed yet.
 * It extracts the deployment zip and then self-destructs.
 * 
 * DO NOT MODIFY - This file is auto-generated by the deployer package.
 */

class InitDeploy
{
    private $token = '{{DEPLOY_TOKEN}}';
    private $zipName = '{{ZIP_NAME}}';

    public function run()
    {
        header('Content-Type: application/json');

        // Get token from query or header
        $providedToken = $_GET['token'] ?? $_SERVER['HTTP_X_DEPLOY_TOKEN'] ?? '';

        // Timing-safe token comparison (pure PHP, no Laravel)
        if (!$this->validateToken($providedToken)) {
            http_response_code(401);
            $this->respond(false, 'Unauthorized: Invalid or missing token');
            return;
        }

        // Allow override via query param, fallback to embedded value
        $zipName = $_GET['zip'] ?? $this->zipName;
        
        // Zip is in parent directory (Laravel root), we're in public/
        $zipPath = dirname(__DIR__) . '/' . $zipName;
        $extractTo = dirname(__DIR__);

        // Validate zip exists
        if (!file_exists($zipPath)) {
            $this->respond(false, "Zip file not found: {$zipName}", [
                'searched_path' => $zipPath
            ]);
            return;
        }

        // Check ZipArchive extension
        if (!class_exists('ZipArchive')) {
            $this->respond(false, 'ZipArchive extension not available on server');
            return;
        }

        $startTime = microtime(true);

        // Extract zip
        $zip = new ZipArchive();
        $openResult = $zip->open($zipPath);
        
        if ($openResult !== true) {
            $this->respond(false, 'Cannot open zip file', [
                'error_code' => $openResult
            ]);
            return;
        }

        $fileCount = $zip->numFiles;
        
        if (!$zip->extractTo($extractTo)) {
            $zip->close();
            $this->respond(false, 'Failed to extract zip contents');
            return;
        }

        $zip->close();

        $elapsed = round(microtime(true) - $startTime, 2);

        // Cleanup: delete the zip file
        $zipDeleted = @unlink($zipPath);

        // Self-destruct: delete this init file
        $selfDeleted = @unlink(__FILE__);

        $this->respond(true, 'Initial deployment completed successfully', [
            'files_extracted' => $fileCount,
            'duration_seconds' => $elapsed,
            'zip_deleted' => $zipDeleted,
            'init_file_deleted' => $selfDeleted,
            'extract_path' => $extractTo
        ]);
    }

    private function validateToken($provided)
    {
        if (empty($provided) || empty($this->token)) {
            return false;
        }
        
        // Timing-safe string comparison
        return hash_equals($this->token, $provided);
    }

    private function respond($success, $message, $data = [])
    {
        echo json_encode(array_merge([
            'success' => $success,
            'message' => $message
        ], $data), JSON_PRETTY_PRINT);
    }
}

// Execute
(new InitDeploy())->run();
